### PR TITLE
Develop 16 new parameter for player

### PR DESCRIPTION
**Pull request by naderzare**

### CODE REVIEW

**Comment by naderzare** [comment]
you have to run cmake and build it at least one time, and commit the generated files by grpc and thrift

**Comment by naderzare** [comment]
also, the version on the first line of thrift and grpc should be 1.1

and the thrift file and grpc file in sample projects should be updated (and codes should be generated)

**Review by SoroushMazloum — COMMENTED** [review]
service.proto and soccer_service.thrift versions are updated.

**Comment by SoroushMazloum** [comment]
I will create another PR to develop-16-new-parameter-for-player branch for adding the thrift and grpc generated files.

**Pull request closed without merging**
