### PR TITLE
Develop chain serverside

### PR DESCRIPTION
**Pull request by naderzare**
By using this PR

grpc server can ask proxy to send back the list of possible actions(chain actions)
and then the server should choose one of them

current version in master
graph 
```mermaid
sequenceDiagram
  participant ss2dServer
  participant proxy
  participant playmaker

  ss2dServer->>proxy: Send observations
  proxy->>playmaker: Send state
  playmaker->>proxy: Send actions
  Note over proxy: create chain actions and find best
  proxy->>ss2dServer: Send actions
```

```mermaid
sequenceDiagram
  participant ss2dServer
  participant proxy
  participant playmaker
  ss2dServer->>proxy: Send observations
  proxy->>playmaker: Send state
  playmaker->>proxy: Send actions (server_side_decision=true)
  Note over proxy: create chain actions
  proxy->>playmaker: Send actions
  Note over playmaker: find best action
  playmaker->>proxy: best action index
  proxy->>ss2dServer: Send actions
```

### CODE REVIEW

**Comment by Arefsa78** [comment]
- Make  ```RpcPlayerClient``` generative and move the ```getAction``` and ```getBestChain``` to that class.
We can handle the Thrift/gRpc objects in the generative class I guess. I can check.
- Make a thread after sending the first state to the ```playmaker``` and start generating chain actions until it gets the response from ```playmaker```

**Comment by Arefsa78** [comment]
@naderzare 
example for Item 2:
```cpp
#include <iostream>

using namespace std;

class StateA {
public:
    int s;
    StateA(int _s) {
        s = _s;
    }
};

class StateB {
public:
    int s;
    StateB(int _s) {
        s = _s;
    }
};

template <typename T>
class ObjectGenerator{
public:
    ObjectGenerator() {
        cout << "ObjectGenerator::ObjectGenerator()" << endl;
    }

    T* generate(int s) {
        if constexpr (is_same<T, StateA>::value) {
            return ObjectGenerator<T>::stateA_generator(s);
        } else if constexpr (is_same<T, StateB>::value) {
            return ObjectGenerator<T>::stateB_generator(s*10);
        }
    }

    static
    StateA* stateA_generator(int s) {
        return new T(s);
    }

    static
    StateB* stateB_generator(int s) {
        return new T(s);
    }
};

class A: public ObjectGenerator<StateA> {
public:
    StateA *state;

    A(int s) {
        cout << "A::A()" << endl;
        state = generate(s);
    }
};

class B : public ObjectGenerator<StateB> {
public:
    StateB *state;
    B(int s) {
        cout << "B::B()" << endl;
        state = generate(s);
    }
};

int main() {
    A a = A(12);
    B b = B(123);

    cout << a.state->s << " " << b.state->s << endl;

}
```

**Comment by naderzare** [comment]
> * Make  `RpcPlayerClient` generative and move the `getAction` and `getBestChain` to that class.
>   We can handle the Thrift/gRpc objects in the generative class I guess. I can check.
> * Make a thread after sending the first state to the `playmaker` and start generating chain actions until it gets the response from `playmaker`
>   @naderzare

The second on is not possible, because we don't know how the server wants to create the tree

**Comment by Arefsa78** [comment]
They are not shooting yet :(

**Pull request merged**
